In [3]:
import pandas as pd
import numpy as np
movie = pd.read_csv('/content/imdb-top-1000.csv')
deliv  = pd.read_csv('/content/deliveries.csv')

In [12]:
movie.head(1)
# group by works on categorical data
genre = movie.groupby('Genre')
genre # group by pandas object

In [44]:
#using functions on genre
genre.sum()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0

In [37]:
#top 3 genre with most earning
genre.sum().sort_values(['Gross'],ascending=False).head(3)
#genre with highest avg imd rating
genre['IMDB_Rating'].mean().sort_values(ascending=False).head(1)
#director with most popularity
movie.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [45]:
#find highest rated movie of each genre:
genre.max()['Series_Title']

Genre
Action                                   Yôjinbô
Adventure                             Zombieland
Animation            Ôkami kodomo no Ame to Yuki
Biography                                Zerkalo
Comedy                  Zindagi Na Milegi Dobara
Crime                          À bout de souffle
Drama                                  Zwartboek
Family       Willy Wonka & the Chocolate Factory
Fantasy                                Nosferatu
Film-Noir                          The Third Man
Horror                                 The Thing
Mystery                                  Vertigo
Thriller                         Wait Until Dark
Western                   The Outlaw Josey Wales
Name: Series_Title, dtype: object

In [57]:
#find number of movies done by each actor
movie.groupby('Star1')['Series_Title'].count()

Star1
Aamir Khan              7
Aaron Taylor-Johnson    1
Abhay Deol              1
Abraham Attah           1
Adam Driver             1
                       ..
Zbigniew Zamachowski    1
Zooey Deschanel         1
Çetin Tekindor          1
Éric Toledano           1
Ömer Faruk Sorak        1
Name: Series_Title, Length: 660, dtype: int64

In [59]:
 #find total number of groups -> len
len(movie.groupby('Genre'))

14

In [66]:
#total rows in each group
movie.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [75]:
#first movie of each groups form
genre.first()
#Last movie of each group
genre.last()
# nth movie of each group

genre.nth(6)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [77]:
#get films of particular genre
genre.get_group('Horror') # fast as it is already grouped

# or
movie[movie['Genre']=='Horror'] # takes time ,first filter than apply so slow

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
844,Halloween,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
876,The Invisible Man,1933,71,Horror,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0

In [82]:
genre.groups # gives a dict , where key is genre and value is list of indecs of the movies whihc fall unde this catergory

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [93]:
genre.nunique()# GIVES unique value
genre.sample()# random movie from each genre
genre.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [103]:
genre.agg(['mean' , 'max' ,'min'])

In [101]:
genre = movie.groupby('Genre')
genre.agg({'Runtime': 'mean', 'No_of_Votes': 'sum', 'IMDB_Rating': 'max'})

              Runtime  No_of_Votes  IMDB_Rating
Genre
Action     129.046512     72282412          9.0
Adventure  134.111111     22576163          8.6
Animation   99.585366     21978630          8.6
Biography  136.022727     24006844          8.9
Comedy     112.129032     27620327          8.6
Crime      126.392523     33533615          9.2
Drama      124.737024     61367304          9.3
Family     107.500000       551221          7.8
Fantasy     85.000000       146222          8.1
Film-Noir  104.000000       367215          8.1
Horror     102.090909      3742556          8.5
Mystery    119.083333      4203004          8.4
Thriller   108.000000        27733          7.8
Western    148.250000      1289665          8.8

In [104]:
genre.agg({'RunTime':'mean' , "No_of_Votes" : 'sum' , 'IMDB_Rating':'max'})

KeyError: "Column(s) ['RunTime'] do not exist"