In [22]:
import pandas as pd
import numpy as np
import re
#files
courses = pd.read_csv('/content/courses.csv')
nov = pd.read_csv('/content/reg-month1.csv')
dec = pd.read_csv('/content/reg-month2.csv')
matches = pd.read_csv('/content/matches.csv')
deli  = pd.read_csv('/content/deliveries.csv')
student = pd.read_csv('/content/students.csv')

In [21]:
courses

    course_id       course_name  price
0           1            python   2499
1           2               sql   3499
2           3     data analysis   4999
3           4  machine learning   9999
4           5           tableau   2499
5           6          power bi   1899
6           7          ms sxcel   1599
7           8            pandas   1099
8           9            plotly    699
9          10           pyspark   2499
10         11             Numpy    699
11         12               C++   1299

In [37]:
df1 = pd.DataFrame(
    {
        'name': ['jibran','samar','ali'],
        'Father_name':['Saleem' , 'abc' ,'xyz']
    }
)
df2 = pd.DataFrame(
    {
        "Age": [40,50,60],
        'name' : [ 'jawwad','samar','ali'],
        'Educaion': ['undergradute','postgraduate','under']
    }
)
df1
df1.merge(df2,on ='name',how='left')

     name Father_name   Age      Educaion
0  jibran      Saleem   NaN           NaN
1   samar         abc  50.0  postgraduate
2     ali         xyz  60.0         under

In [36]:
df2

   Age    name      Educaion
0   40  jawwad  undergradute
1   50   samar  postgraduate
2   60     ali         under

In [40]:
#concat
total_regs = pd.concat([nov,dec],ignore_index = True).sort_values(by='student_id')
#inner join
total_regs.merge(courses,on = 'course_id',how = 'inner')

    student_id  course_id       course_name  price
0            1          9            plotly    699
1            1         10           pyspark   2499
2            1          1            python   2499
3            1          6          power bi   1899
4            2          5           tableau   2499
5            3          3     data analysis   4999
6            3          5           tableau   2499
7            7          6          power bi   1899
8            7          7          ms sxcel   1599
9            7          8            pandas   1099
10           7          2               sql   3499
11           7         10           pyspark   2499
12          11          8            pandas   1099
13          11          7          ms sxcel   1599
14          11         10           pyspark   2499
15          12          5           tableau   2499
16          12          7          ms sxcel   1599
17          12          1            python   2499
18          12         10           pyspark   2499
19          13          3     data analysis   4999
20          14          1            python   2499
21          14          4  machine learning   9999
22          14          9            plotly    699
23          14          6          power bi   1899
24          15          1            python   2499
25          15          5           tableau   2499
26          16          3     data analysis   4999
27          16          7          ms sxcel   1599
28          16          5           tableau   2499
29          16          9            plotly    699
30          17          7          ms sxcel   1599
31          17         10           pyspark   2499
32          18          1            python   2499
33          18          8            pandas   1099
34          18          6          power bi   1899
35          19          2               sql   3499
36          19          4  machine learning   9999
37          21          1            python   2499
38          22          6          power bi   1899
39          22          3     data analysis   4999
40          22          5           tableau   2499
41          23          5           tableau   2499
42          23          9            plotly    699
43          23          1            python   2499
44          23          6          power bi   1899
45          23          3     data analysis   4999
46          23          4  machine learning   9999
47          24          4  machine learning   9999
48          25         10           pyspark   2499
49          25          1            python   2499
50          38          1            python   2499
51          42          9            plotly    699
52          50          8            pandas   1099

In [ ]:
#left join : all elements from left and jo match kr rha h , col uski keys match kro sare elemets s if left key is present in right then all rows are add in it
#if lefy key does not found in right right dataframe then nan is placed
df1 = pd.DataFrame(
    {
        'name': ['jibran','samar','ali'],
        'Father_name':['Saleem' , 'abc' ,'xyz']
    }
)
df2 = pd.DataFrame(
    {
        "Age": [40,50,60],
        'name' : [ 'jawwad','samar','ali'],
        'Educaion': ['undergradute','postgraduate','under']
    }
)

df1.merge(df2,on ='name',how='left')
#left
# total_regs
courses.merge(total_regs,on="course_id",how='left')   # course_id course_name price student_id
total_regs

In [ ]:
#right join
#same as left but all right are included

#outer :
#all from right and left are included

In [47]:
#TOTAL REVENEW GEN BY THE COURESES

total_regs
# student
# courses : # course id , course name , price
x = total_regs.merge(courses,on ='course_id',how='inner')
x.groupby('course_name')['price'].sum().sum()

154247

In [61]:
#month by month reg
pd.concat([nov,dec],keys=['nov','dec']).reset_index().merge(courses,on ='course_id',how='inner').groupby('level_0')['price'].sum()

level_0
dec    65072
nov    89175
Name: price, dtype: int64

In [77]:
#print regis table
#cols - > name -> course  - > price

student # std id ,std name , partner
courses#  course id , course name price
total_regs #student id and course id
total_regs.merge(student,on='student_id',how='inner').merge(courses,on = 'course_id' , how = 'inner')[['name','course_name','price']]

                  name       course_name  price
0        Kailash Harjo            plotly    699
1        Kailash Harjo           pyspark   2499
2        Kailash Harjo            python   2499
3        Kailash Harjo          power bi   1899
4          Esha Butala           tableau   2499
5       Parveen Bhalla     data analysis   4999
6       Parveen Bhalla           tableau   2499
7         Tarun Thaker          power bi   1899
8         Tarun Thaker          ms sxcel   1599
9         Tarun Thaker            pandas   1099
10        Tarun Thaker               sql   3499
11        Tarun Thaker           pyspark   2499
12  David Mukhopadhyay            pandas   1099
13  David Mukhopadhyay          ms sxcel   1599
14  David Mukhopadhyay           pyspark   2499
15          Radha Dutt           tableau   2499
16          Radha Dutt          ms sxcel   1599
17          Radha Dutt            python   2499
18          Radha Dutt           pyspark   2499
19      Munni Varghese     data analysis   4999
20    Pranab Natarajan            python   2499
21    Pranab Natarajan  machine learning   9999
22    Pranab Natarajan            plotly    699
23    Pranab Natarajan          power bi   1899
24           Preet Sha            python   2499
25           Preet Sha           tableau   2499
26        Elias Dodiya     data analysis   4999
27        Elias Dodiya          ms sxcel   1599
28        Elias Dodiya           tableau   2499
29        Elias Dodiya            plotly    699
30        Yasmin Palan          ms sxcel   1599
31        Yasmin Palan           pyspark   2499
32     Fardeen Mahabir            python   2499
33     Fardeen Mahabir            pandas   1099
34     Fardeen Mahabir          power bi   1899
35        Qabeel Raman               sql   3499
36        Qabeel Raman  machine learning   9999
37          Seema Kota            python   2499
38          Yash Sethi          power bi   1899
39          Yash Sethi     data analysis   4999
40          Yash Sethi           tableau   2499
41      Chhavi Lachman           tableau   2499
42      Chhavi Lachman            plotly    699
43      Chhavi Lachman            python   2499
44      Chhavi Lachman          power bi   1899
45      Chhavi Lachman     data analysis   4999
46      Chhavi Lachman  machine learning   9999
47        Radhika Suri  machine learning   9999
48     Shashank D’Alia           pyspark   2499
49     Shashank D’Alia            python   2499

In [86]:
#find stundets take course in both month
ids = np.intersect1d(nov['student_id'],dec['student_id'])
student[student['student_id'].isin(ids)]

    student_id                name  partner
0            1       Kailash Harjo       23
2            3      Parveen Bhalla        3
6            7        Tarun Thaker        9
10          11  David Mukhopadhyay       20
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18

In [102]:
#course with no enrol

courses
total_regs
x  = np.setdiff1d(courses['course_id'],total_regs['course_id'])
courses[courses['course_id'].isin(x)]

    course_id course_name  price
10         11       Numpy    699
11         12         C++   1299

In [114]:
#print partner name  using inner join

student.merge(student , how = 'inner' , left_on = 'partner' , right_on = 'student_id')[['name_x','name_y']]

matches

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [113]:
#find stadium with highest sixes/fours ratio
deli

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN